import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,mkdtemp,readFile,writeFile} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {_electron as electron,expect} from '@playwright/test';

test('actual Electron sample journey and sandbox rendering',async()=>{
  await mkdir('.test-data/gui',{recursive:true});await mkdir('aidlc-docs/construction/mindcraft/evidence/screenshots',{recursive:true});
  const root=await mkdtemp(resolve('.test-data/gui/case-'));
  const env=Object.fromEntries(Object.entries(process.env).filter((entry):entry is [string,string]=>entry[1]!==undefined&&entry[0]!=='ELECTRON_RUN_AS_NODE'));
  const app=await electron.launch({args:[resolve('dist/main.js'),'--workspace',root,'--profile',join(root,'profile')],env,timeout:30000});
  const errors:string[]=[];
  try{
    const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));
    await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setContentSize(1440,900));
    await expect(page.getByTestId('home')).toBeVisible({timeout:20000});
    await page.screenshot({path:'aidlc-docs/construction/mindcraft/evidence/screenshots/home-1440.png'});
    assert.equal(await page.evaluate(()=>typeof (window as any).require),'undefined');
    assert.equal(await page.evaluate(()=>typeof (window as any).process),'undefined');
    const malformed=await page.evaluate(()=>window.mindcraft.request({protocol:2,requestId:crypto.randomUUID(),sessionId:'',command:'secret.put',payload:{providerId:'test',value:'synthetic',unexpected:true}}));
    assert.equal(malformed.ok,false);if(!malformed.ok)assert.equal(malformed.error.code,'invalidInput');
    await page.getByTestId('home-sample-button').click();
    await expect(page.getByTestId('workspace-context-confirm-button')).toBeVisible({timeout:20000});
    await expect(page.locator('.source-card')).toHaveCount(3);
    await page.getByTestId('workspace-context-confirm-button').click();
    await expect(page.locator('.status.completed')).toBeVisible({timeout:20000});
    await expect(page.getByTestId('output-latest')).toBeVisible({timeout:20000});
    await page.getByTestId('output-latest').click();
    await expect(page.locator('.markdown')).toContainText('온담',{timeout:20000});
    await expect(page.getByRole('button',{name:'파일로 저장',exact:true})).toBeEnabled({timeout:20000});
    await page.getByRole('button',{name:'처음부터 읽기'}).click();
    await expect(page.getByTestId('output-cancel')).toBeHidden();
    await expect(page.getByTestId('output-position')).toHaveText('전체 결과');
    await expect(page.getByTestId('output-start')).toHaveCount(0);
    await page.getByRole('region',{name:'작업 결과 읽기'}).focus();
    await expect(page.getByRole('region',{name:'작업 결과 읽기'})).toBeFocused();
    await page.keyboard.press('PageDown');
    await expect.poll(()=>page.getByTestId('workspace-output').evaluate(el=>el.scrollTop)).toBeGreaterThan(0);
    await page.getByRole('button',{name:'처음부터 읽기'}).click();
    await expect(page.getByTestId('output-cancel')).toBeHidden();
    await page.evaluate(()=>window.scrollTo(0,0));
    await page.screenshot({path:'aidlc-docs/construction/mindcraft/evidence/screenshots/workspace-1440.png'});
    await page.getByRole('button',{name:'파일로 저장',exact:true}).click();
    await page.getByTestId('workspace-dialog-input').fill('GUI 준비안.md');
    await page.getByTestId('workspace-dialog-submit').click();
    await expect(page.getByTestId('approval-deny-button')).toBeVisible();
    await page.screenshot({path:'aidlc-docs/construction/mindcraft/evidence/screenshots/approval-1440.png'});
    await page.getByTestId('approval-approve-button').click();
    await expect.poll(async()=>{try{return await readFile(join(root,'GUI 준비안.md'),'utf8');}catch{return '';}}).toContain('온담');
    await page.getByTestId('nav-history').click();
    await page.getByRole('searchbox',{name:'작업 검색'}).fill('일치하지않는검색어');
    await expect(page.getByText('검색과 일치하는 작업이 없어요')).toBeVisible();
    await expect(page.getByText('아직 기록된 작업이 없어요')).toHaveCount(0);
    await page.getByRole('button',{name:'검색 초기화'}).click();
    await expect(page.getByRole('searchbox',{name:'작업 검색'})).toBeFocused();
    await expect(page.getByTestId('history-selected-task')).toContainText('온담');
    await page.screenshot({path:'aidlc-docs/construction/mindcraft/evidence/screenshots/history-1440.png'});
    await page.getByRole('button',{name:'실행 결과 열기'}).first().click();
    await expect(page.getByTestId('workspace')).toBeVisible();
    await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.setContentSize(1024,700);w.webContents.setZoomFactor(2);});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1),true);
    await page.getByRole('button',{name:'파일로 저장',exact:true}).click();
    await page.getByTestId('workspace-dialog-input').fill('확대 화면 거부.md');
    await page.getByTestId('workspace-dialog-submit').click();
    await expect(page.getByTestId('approval-deny-button')).toBeVisible();
    await page.getByTestId('approval-deny-button').click();
    await assert.rejects(()=>readFile(join(root,'확대 화면 거부.md')),(error:any)=>error.code==='ENOENT');
    await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.webContents.setZoomFactor(1);w.setContentSize(1440,900);});
    await page.getByTestId('nav-setup').click();
    await page.screenshot({path:'aidlc-docs/construction/mindcraft/evidence/screenshots/setup-1440.png'});
    await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setContentSize(1024,700));
    await page.screenshot({path:'aidlc-docs/construction/mindcraft/evidence/screenshots/setup-1024.png'});
    await page.getByTestId('nav-home').click();
    await page.screenshot({path:'aidlc-docs/construction/mindcraft/evidence/screenshots/home-1024.png'});
    await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].webContents.setZoomFactor(2));
    await expect(page.getByTestId('home-request-input')).toBeVisible();
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1),true);
    const zoomCapture=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].webContents.capturePage()).toPNG().toString('base64'));
    await writeFile('aidlc-docs/construction/mindcraft/evidence/screenshots/home-1024-zoom200.png',Buffer.from(zoomCapture,'base64'));
    assert.deepEqual(errors,[]);
  }finally{await app.close();}
});
