import {createRequire} from 'node:module';import fs from 'node:fs';import http from 'node:http';import path from 'node:path';import assert from 'node:assert/strict';
const require=createRequire('C:/ai/ai-dlc-09-09/mindcraft/package.json');const {chromium}=require('playwright');
const manifest=JSON.parse(fs.readFileSync('video/product-demo-v4/manifest.json','utf8'));const seconds=Math.ceil(manifest.duration);const base=path.resolve('site');
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');const file=path.join(base,decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(base+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}const stat=fs.statSync(file);const types={'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.mp4':'video/mp4','.jpg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml'};const headers={'Content-Type':types[path.extname(file)]||'application/octet-stream','Accept-Ranges':'bytes'};const range=req.headers.range;if(range){const [a,b]=range.replace('bytes=','').split('-');const start=Number(a),end=b?Number(b):stat.size-1;res.writeHead(206,{...headers,'Content-Range':`bytes ${start}-${end}/${stat.size}`,'Content-Length':end-start+1});fs.createReadStream(file,{start,end}).pipe(res);}else{res.writeHead(200,{...headers,'Content-Length':stat.size});fs.createReadStream(file).pipe(res);}}).listen(0,'127.0.0.1');
await new Promise(r=>server.once('listening',r));const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{const errors=[];const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.locator('#product-video').evaluate(v=>new Promise(resolve=>{if(v.readyState>=1)resolve();else v.addEventListener('loadedmetadata',resolve,{once:true});}));
const before=await page.locator('#product-video').evaluate(v=>({duration:v.duration,width:v.videoWidth,height:v.videoHeight,paused:v.paused,loop:v.loop}));assert.ok(Math.abs(before.duration-manifest.duration)<0.15);assert.equal(before.width,1920);assert.equal(before.height,1080);assert.equal(before.paused,true);assert.equal(before.loop,false);assert.equal(await page.locator('.demo-shot[open]').count(),0);assert.equal(await page.locator('.hero-animation a[href=\"#product-film\"]').count(),0);assert.ok(await page.locator('#concept-video').evaluate(v=>v.muted&&v.loop&&v.currentSrc.includes('hero-animation-v1.mp4')));
await page.locator('#product-film').scrollIntoViewIfNeeded();await page.locator('#product-video').evaluate(v=>v.play());await page.waitForTimeout(1300);assert.ok(await page.locator('#product-video').evaluate(v=>v.currentTime>0&&!v.paused));await page.locator('#product-video').evaluate(v=>{v.pause();v.currentTime=30;});await page.waitForTimeout(500);assert.ok(await page.locator('#product-video').evaluate(v=>Math.abs(v.currentTime-30)<.5));await page.locator('#product-film').screenshot({path:'video/product-demo-v4/page-desktop.png'});
await page.setViewportSize({width:390,height:844});await page.goto(`http://127.0.0.1:${server.address().port}/`);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#product-film').scrollIntoViewIfNeeded();await page.screenshot({path:'video/product-demo-v4/page-mobile.png'});await page.emulateMedia({reducedMotion:'reduce'});await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.waitForTimeout(350);assert.ok(await page.locator('#concept-video').evaluate(v=>v.paused));assert.deepEqual(errors,[]);fs.writeFileSync('video/product-demo-v4/verification.json',JSON.stringify({video:before,playback:true,seeking:true,mobileOverflow:false,pageErrors:errors},null,2));console.log('PASS: 1080p metadata, manual playback, seek, mobile layout, no page errors');
await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:1440,height:1000});await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.locator('.quick-overview').screenshot({path:'video/product-demo-v4/overview-desktop.png'});assert.equal(await page.locator('[data-overview]').count(),5);await page.locator('[data-overview="2"]').click();assert.equal(await page.locator('#tab-2').getAttribute('aria-selected'),'true');await page.locator('#knowledge-proof summary').click();assert.ok(await page.locator('#knowledge-proof img').isVisible());await page.setViewportSize({width:390,height:844});await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.locator('.quick-overview').screenshot({path:'video/product-demo-v4/overview-mobile.png'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.goto(`http://127.0.0.1:${server.address().port}/details.html`);assert.equal(await page.locator('#workflow-principle details').first().getAttribute('open'),null);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));console.log('PASS: summary links select features, knowledge proof expands, optional principle closed, mobile details fit');
}finally{await browser.close();server.close();}
