import {createRequire} from 'node:module';import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';
const require=createRequire('C:/ai/ai-dlc-09-09/mindcraft/package.json');const {chromium}=require('playwright');const root=path.resolve('site');
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');const p=path.resolve(root,'.'+(u.pathname==='/'?'/index.html':decodeURIComponent(u.pathname)));if(!p.startsWith(root+path.sep)||!fs.existsSync(p)){res.writeHead(404);res.end();return;}const length=fs.statSync(p).size;const types={'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.mp4':'video/mp4','.jpg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml'};const h={'Content-Type':types[path.extname(p)]||'application/octet-stream','Accept-Ranges':'bytes'};if(req.headers.range){const [a,b]=req.headers.range.slice(6).split('-');const start=Number(a),end=b?Number(b):length-1;res.writeHead(206,{...h,'Content-Range':`bytes ${start}-${end}/${length}`,'Content-Length':end-start+1});fs.createReadStream(p,{start,end}).pipe(res);}else{res.writeHead(200,{...h,'Content-Length':length});fs.createReadStream(p).pipe(res);}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/`);
 await page.waitForFunction(()=>document.querySelector('#product-video').readyState>=2);const desktop=await page.locator('#product-video').evaluate(v=>({src:v.currentSrc,duration:v.duration,width:v.videoWidth,height:v.videoHeight,paused:v.paused}));assert.equal(desktop.width,1920);assert.ok(desktop.paused);assert.ok(Math.abs(desktop.duration-50.1)<.04);
 await page.locator('#product-film').scrollIntoViewIfNeeded();await page.locator('#product-video').evaluate(async v=>{await v.play();});await page.waitForTimeout(500);assert.ok(await page.locator('#product-video').evaluate(v=>v.currentTime>0));await page.locator('#product-video').evaluate(v=>{v.pause();v.currentTime=22;});await page.waitForTimeout(350);await page.locator('#product-film').screenshot({path:'video/product-demo-v5/page-desktop.png'});
 await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>{const v=document.querySelector('#product-video');return v.videoHeight===1440&&v.readyState>=2;});await page.waitForFunction(()=>{const v=document.querySelector('#product-video');return !v.seeking&&v.readyState>=3;});await page.waitForTimeout(1200);const mobile=await page.locator('#product-video').evaluate(v=>({src:v.currentSrc,width:v.videoWidth,height:v.videoHeight,time:v.currentTime,paused:v.paused,boxWidth:v.getBoundingClientRect().width,boxHeight:v.getBoundingClientRect().height,poster:v.poster}));assert.ok(mobile.src.includes('-mobile.mp4'));assert.ok(mobile.poster.includes('-mobile.jpg'));assert.equal(mobile.width,1080);assert.ok(Math.abs(mobile.time-22)<.2);assert.ok(mobile.paused);assert.ok(Math.abs(mobile.boxHeight/mobile.boxWidth-4/3)<.01);assert.ok(37*mobile.boxWidth/1080>=11);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#product-film').scrollIntoViewIfNeeded();await page.locator('#product-film').screenshot({path:'video/product-demo-v5/page-mobile.png'});
 await page.locator('#product-video').evaluate(v=>v.play());await page.setViewportSize({width:1440,height:1000});await page.waitForFunction(()=>{const v=document.querySelector('#product-video');return v.videoWidth===1920&&v.readyState>=2&&!v.paused;});assert.ok(await page.locator('#product-video').evaluate(v=>v.currentTime>=22));assert.deepEqual(errors,[]);assert.ok(await page.locator('#concept-video').evaluate(v=>v.paused&&v.currentSrc.includes('hero-final-v2.mp4')));
 const noJS=await browser.newPage({javaScriptEnabled:false});await noJS.goto(`http://127.0.0.1:${server.address().port}/`);assert.equal(await noJS.locator('a[href="./assets/product-demo-v5-mobile.mp4"]').count(),1);await noJS.close();
 fs.writeFileSync('video/product-demo-v5/site-verification.json',JSON.stringify({desktop,mobile,responsiveTimePreserved:true,playbackAndSeeking:true,noJSAlternative:true,pageErrors:errors},null,2));console.log('PASS: playback, seek, responsive variant and time preservation, portrait readability, no-JS fallback, no errors');
}finally{await browser.close();server.close();}
